package com.eventhall.repository;

import com.eventhall.entity.Quote;
import com.eventhall.enums.QuoteStatus;
import org.springframework.data.jpa.repository.JpaRepository;

import java.time.LocalDateTime;
import java.util.List;

/*
 * Repository for Quote entities.
 *
 * This is the main repository for submitted customer quote requests.
 */
public interface QuoteRepository extends JpaRepository<Quote, Long> {

    /*
     * Custom finder method generated by Spring Data JPA.
     *
     * findByStatus means:
     * "Select all Quote rows where the status column equals the given status."
     *
     * This is used by the admin endpoint:
     * GET /api/admin/quotes?status=CONTACTED
     */
    List<Quote> findByStatus(QuoteStatus status);

    List<Quote> findByApprovedAtBetween(LocalDateTime start, LocalDateTime end);
}