services:
  postgres:
    image: postgres:16
    container_name: eventhall-postgres
    environment:
      POSTGRES_DB: eventhall_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - eventhall_postgres_data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/jordandaudu/eventhall-backend:latest
    container_name: eventhall-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eventhall_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      BUSINESS_NAME: Event Hall Demo
      BUSINESS_CONTACT_EMAIL: contact@example.com
      BUSINESS_CONTACT_PHONE: 0500000000
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/jordandaudu/eventhall-frontend:latest
    container_name: eventhall-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  eventhall_postgres_data: